# Generated by Django 4.2 on 2023-05-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/')),
                ('birth', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('website', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CareerDetails',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100)),
                ('skillpercent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmname', models.CharField(max_length=100)),
                ('tmexpertise', models.CharField(max_length=100)),
                ('tmdesc', models.TextField(max_length=300)),
                ('tmimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
